### ISSUE TITLE
`Cannot use object of type Closure as array` when using filters

### ISSUE THREAD

**Issue by jakubvojacek** [efabrica-team/phpstan-latte#100]
Hello

I get 

```
 ------ -------------------------------------------------------------------------------------- 
  Line   PersonsGrid.latte rendered from Motv\FrontModule\Components\Vods\PersonsGrid::render  
 ------ -------------------------------------------------------------------------------------- 
  -1     Cannot use object of type Closure as array                                            
 ------ -------------------------------------------------------------------------------------- 
```

on a very simple file

```
{if $person !== null}
	{$person->getBirthday()|datetime}
{/if}
```

I cannot share the generated file because none is generated actually. 

The filter `|datetime` is register as latte3 extension and defined as

```php
/** @param mixed $datetime */
	public static function formatDateTime($datetime): string
	{
		if ($datetime === null) {
			return 'N/A';
		}

		if ($datetime instanceof \DateTime || $datetime instanceof \DateTimeImmutable) {
			$datetime = $datetime->format('c');
		}

		if (\is_string($datetime)) {
			$datetime = strtotime($datetime);
		}

		return date('D, j M Y G:i:s', $datetime);
	}


...
                         'datetime' => static function ($date): string {
				return Helper::formatDateTime($date);
			},
...
```

**Comment by MartinMystikJonas** [comment]
Can you share function `getFilters` from your extension? It seems you are returning filter enveloped in Closure (first class callable?) and not as simple callable array `[class, method]`. Closure filters are not yet supported (#57).

**Comment by jakubvojacek** [comment]
```php

class InstallLatteFilterMacros extends Latte\Extension
{

	/** @var array<string, string>|null */
	private ?array $countries = null;

	/** @var array<int, string>|null */
	private ?array $genres = null;

	/** @var array<int, string>|null */
	private ?array $advertUnits = null;

	/** @var array<int|string, string> */
	private array $profiles = [];

	public function __construct(
		private Motv\FrontModule\Model\Profile $modelProfile,
		private Motv\FrontModule\Model\Translator $modelTranslator,
		private Motv\FrontModule\Model\Country $modelCountry,
		private Motv\FrontModule\Model\EpgPlaylist $modelEpgPlaylist,
		private Motv\FrontModule\Model\Channel $modelChannel,
		private Motv\FrontModule\Model\Genre $modelGenre,
		private Motv\FrontModule\Model\Advert $modelAdvert,
		private Motv\FrontModule\Model\AdvertHomepage $modelAdvertHomepage,
		private Motv\FrontModule\Model\User $modelUser,
		private Motv\FrontModule\Model\Template $modelTemplate,
		private Motv\FrontModule\Model\Category $modelCategory,
		private Motv\FrontModule\Model\Config $modelConfig,
		private Motv\FrontModule\Model\VodGroup $modelVodGroup,
		private Motv\FrontModule\Model\Package $modelPackage
	)
	{
	}

	/** @return array<string, callable> */
	public function getFilters(): array
	{
               return [
                   'datetime' => static function ($date): string {
				return Helper::formatDateTime($date);
			},
              ];

```

it returns many other filters apart from `datetime` but thats not relevant i guess.

I just read the difference in between callable and closure and I believe I am using a `Closure` right? Since its an anonymous function (this is how we define most of the filters).

Since this is not supposed to be supported, please feel free to close the ticket as irrelevant.

**Comment by MartinMystikJonas** [comment]
It should work if you return callable array
```php
        /** @return array<string, callable> */
	public function getFilters(): array
	{
               return [
                   'datetime' => [Helper::class, 'formatDateTime']
              ];
```

**Comment by jakubvojacek** [comment]
yes, it works. It will be quite some work to rewrite all these filters to standalone methods but I will do that for the sake of static analysis :)

**Comment by MartinMystikJonas** [comment]
Well you can wait till we implement it ;-)

**Comment by jakubvojacek** [comment]
Does it have to be a static function or the `[class, 'xxx'] format`? I tried to convert it like this:

```
	/** @return array<string, callable> */
	public function getFilters(): array
	{
		return [
			'markdown' => $this->markdown(...),
			'profilesName' => $this->profilesName(...),
			'campaign' => $this->campaign(...),
			'package' => $this->package(...),
```

but still getting `Cannot use object of type Closure as array`

**Comment by MartinMystikJonas** [comment]
First class callables `$this->markdown(...)` are internally handled like Closures. In config `[class, method]` should work even for non-static methods but I am afraid it will not handle `[$this, 'markdown']` at the moment. I will look at it tommorow. Support for `[$this, 'markdown']` should be quiter easy do to. And maybe I will figure our how to handle Closures too.

**Comment by jakubvojacek** [comment]
I tried before `[$this, 'markdown']` but latte does not handle that due to `[Latte\Runtime\FilterExecutor::add](editor://open/?file=%2FUsers%2Fjakubvojacek%2FSites%2Fmotvmw-gui%2Fvendor%2Flatte%2Flatte%2Fsrc%2FLatte%2FRuntime%2FFilterExecutor.php&line=34&search=&replace=)(): Argument #2 ($callback) must be of type callable, array given, called in`

**Comment by MartinMystikJonas** [comment]
@jakubvojacek Can you test branch dev-filters - I rewrote mechanism working with filters to support closures and better automatic detection of filters. It should work for filters added by addFilter as well as from extensions and handle closures. Tests passes but I would like to see results on real app.

**Comment by MartinMystikJonas** [comment]
@jakubvojacek Already in main

**Comment by jakubvojacek** [comment]
Testing already, running into some issues

```
In TokenIterator.php line 158:
                                                                 
  Unexpected token ".widevine.alpha:", expected '}' at offset 9  
```

which might have been caused by my somewhat weird array-shape `return array{'com.widevine.alpha': string, 'com.apple.fps.1_0': string, 'roku'?: string}`. Upon removing this phpdoc, I am running into less readable error:

```
In TokenIterator.php line 158:
  Unexpected token "~null", expected TOKEN_END at offset 5 
```

I tried running phpstan with --debug but it analysed all files and failed afterwards therefore im not sure which file might be the issue

**Comment by MartinMystikJonas** [comment]
This plugin runs collector to first gather all info from analysed PHP files and then uses this to run analysis on latte.

**Comment by MartinMystikJonas** [comment]
Are there any compiled templates in tmp/phpstan-latte after you run this? When run with --debug does it shows you a stack trace?

**Comment by MartinMystikJonas** [comment]
Where exactly you you use that PHPDoc with array shape? Is it render parameter? Passed variable? Filter?

**Comment by jakubvojacek** [comment]
no files generated, this is the backtrace

```
Uncaught PHPStan\PhpDocParser\Parser\ParserException: Unexpected token ".widevine.alpha:", expected '}' at offset 9 in phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php:158
#0 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php(63): PHPStan\PhpDocParser\Parser\TokenIterator->throwError(32)
#1 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/vendor/phpstan/phpdoc-parser/src/Parser/TypeParser.php(373): PHPStan\PhpDocParser\Parser\TokenIterator->consumeTokenType(32)
#2 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/vendor/phpstan/phpdoc-parser/src/Parser/TypeParser.php(100): PHPStan\PhpDocParser\Parser\TypeParser->parseArrayShape(Object(PHPStan\PhpDocParser\Parser\TokenIterator), Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode))
#3 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/vendor/phpstan/phpdoc-parser/src/Parser/TypeParser.php(25): PHPStan\PhpDocParser\Parser\TypeParser->parseAtomic(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#4 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeStringResolver.php(35): PHPStan\PhpDocParser\Parser\TypeParser->parse(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#5 /Users/jakubvojacek/Sites/motvmw-gui/vendor/efabrica/phpstan-latte/src/Collector/ValueObject/CollectedVariable.php(71): PHPStan\PhpDoc\TypeStringResolver->resolve('array{com.widev...')
#6 /Users/jakubvojacek/Sites/motvmw-gui/vendor/efabrica/phpstan-latte/src/Collector/Finder/VariableFinder.php(117): Efabrica\PHPStanLatte\Collector\ValueObject\CollectedVariable::fromArray(Array, Object(PHPStan\PhpDoc\TypeStringResolver))
#7 /Users/jakubvojacek/Sites/motvmw-gui/vendor/efabrica/phpstan-latte/src/Collector/Finder/VariableFinder.php(34): Efabrica\PHPStanLatte\Collector\Finder\VariableFinder->buildData(Array)
#8 /Users/jakubvojacek/Sites/motvmw-gui/vendor/efabrica/phpstan-latte/src/LatteTemplateResolver/AbstractTemplateResolver.php(46): Efabrica\PHPStanLatte\Collector\Finder\VariableFinder->__construct(Object(PHPStan\Node\CollectedDataNode), Object(Efabrica\PHPStanLatte\Collector\Finder\MethodCallFinder), Object(PHPStan\PhpDoc\TypeStringResolver))
#9 /Users/jakubvojacek/Sites/motvmw-gui/vendor/efabrica/phpstan-latte/src/Rule/LatteTemplatesRule.php(89): Efabrica\PHPStanLatte\LatteTemplateResolver\AbstractTemplateResolver->resolve(Object(Efabrica\PHPStanLatte\Collector\ValueObject\CollectedResolvedNode), Object(PHPStan\Node\CollectedDataNode))
#10 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(149): Efabrica\PHPStanLatte\Rule\LatteTemplatesRule->processNode(Object(PHPStan\Node\CollectedDataNode), Object(PHPStan\Analyser\MutatingScope))
#11 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(113): PHPStan\Command\AnalyseApplication->getCollectedDataErrors(Array)
#12 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(168): PHPStan\Command\AnalyseApplication->analyse(Array, false, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, '/Users/jakubvoj...', Array, Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput))
#13 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(868): _PHPStan_582a9cb8b\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->doRun(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->run()
#18 phar:///Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_582a9cb8b\{closure}()
#19 /Users/jakubvojacek/Sites/motvmw-gui/vendor/phpstan/phpstan/phpstan(8): require('phar:///Users/j...')
#20 /Users/jakubvojacek/Sites/motvmw-gui/vendor/bin/phpstan(117): include('/Users/jakubvoj...')
#21 {main}
```

**Comment by jakubvojacek** [comment]
this array shape isnt event used in the filters, its just a return array shape of some  method in the API part, it looks like this https://phpstan.org/r/dd1323a1-d7fd-43ff-9d39-4da6e544967d

**Comment by MartinMystikJonas** [comment]
And result of thic method is assigned to template variable right? It seems that PHPStan collects variable type, outputs it as string and then cannot understand this string when parsed back to type. It seems taht problem is use of `.` in array shape key. it seems taht it forget to add quotes around it in serialized form. Probably related to change in serailization/deserialization of variable types. I will look at it.

**Comment by jakubvojacek** [comment]
yes its assigned to template variable.

But even when I removed the phpdocs from all places, cleared all caches, it still didnt work and I got the `"~null"` error which I didnt find anywhere by fulltext search

**Comment by MartinMystikJonas** [comment]
It would be some resolved type by phpstan that is checked to not to be null.

**Comment by MartinMystikJonas** [comment]
I would need to look at it in more detail. It seems it is either bug of PHpStan or we use it in unexpected way. I will try to find solution to pass detailed type wehn possible and fall back to generic type when not.

**Comment by jakubvojacek** [comment]
Let me know if you need me to test anything please. I myself am not that familiar with phpstan but can test whatever.

Thank you for developing this extension

**Comment by MartinMystikJonas** [comment]
I was able to create failing test case thenks to information already provided. I just have to experiment to find solution. We appreciate all feedback ;-)

**Comment by MartinMystikJonas** [comment]
@jakubvojacek Try branch dev-type-phpdoc. I rewrote internal handling and PHPDOc conversion for complex types so it should not fail but just fall back to less specific type representation allowed in PHPDoc.

**Comment by jakubvojacek** [comment]
on it

**Comment by jakubvojacek** [comment]
Works, I got some 300 errors reported now. Will go through them tomorrow. But its processing files now that it refused before due to this error `Cannot use object of type Closure as array`

Thanks a lot!

**Comment by MartinMystikJonas** [comment]
Great. Report new issues if you find any.
